package xyz.korayucar.regex;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'koray2' at '7/25/16 4:02 PM' with Gradle 2.12
 *
 * @author koray2, @date 7/25/16 4:02 PM
 */
public class RegexLearning {
    public final Logger LOG = LoggerFactory.getLogger(getClass());
    
    public boolean regexLearning() {
        System.console();
        return true;
    }
    
    
    public void findOccurences(String regex, String text) {
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(text);
        boolean found = false;
        LOG.debug("regex is {}" ,regex);
        LOG.debug("text is {}" ,text);
        while (matcher.find()) {
            LOG.debug("I found the text {} starting at " +
                            "index {} and ending at index {}.",
                    matcher.group(),
                    matcher.start(),
                    matcher.end());
            found = true;
        }
        if (!found) {
            LOG.debug("No match found.");
        }
    }
    
}
